title: Raspberry Pi Compute Module 4 NVMe array NAS
description: A simple board for Raspberry Pi Compute Module 4 plus 4x NVMe SSD using ASM1184e

staticman_url: https://staticman-willwhang.herokuapp.com/v2/entry/will127534/CM4-Nvme-NAS/gh-pages/comments
reCaptcha:
  enabled: true
  siteKey: 6Lf4710dAAAAANxRwZDNmXeA0rNATnXxSUylD8MO
  secret: DZX476sONQoXjE7X4vRu5ZSuk24HSWU6PBcY2swun75l6MsiZkOebj5qxYKNlpP7TMz9lZ/BYh514cN7bFqitnHScN2eo5TAIQnYK9H2mECJCMpDWbBAal4LNPqVc6b+L+pNCqbl4tqB4OSrr7KM6jbeJV/tNz+gOrkdFM74zKPDBH2QMD8oCbrrQgiobi4/kvKQovOvgbomvBx35Pr7iVM2LgSWCPAWFI3vMGA60c/+uoTqJ2sW/Vp6ZRLEj715d5PcwrOCf8brMvNL6mQonVwSJCfu8D4unzQ1kzLLdFbjKr092q0jqQLBB40bwPzAJhkIcAzP0o77VLQ/XNG1Ng==


google_analytics: UA-72609315-3
show_downloads: false
author:
  name: Will Whang
  twitter: willwhang
twitter_username: willwhang
github_username:  will127534

